### ISSUE TITLE
Review and polish "Build a counter on the testnet"

### ISSUE THREAD

**Issue by ShalmaliCL** [casper-network/docs-new#10]
Review https://docs.casperlabs.io/counter/

**Comment by ghost** [comment]
According to [PR description](https://github.com/casper-network/docs-new/pull/18), all four 4 pages - _Introduction_, _Overview_,  _Important Commands_, _Walkthrough_ - were reviewed and no changes are required.

**Comment by ShalmaliCL** [comment]
the counter repository is changed and has two contract versions now. Will create a new card to update the content. 
CC: @andrzej-casper @Adrian-Wrona
