### ISSUE TITLE
Migrate from other chain

### ISSUE THREAD

**Issue by Adrian-Wrona** [casper-network/docs-new#147]
Let's discuss:
1. What chain to start with
2. If @ipopescu or @ACStoneCL know if we have any materials available
3. Where should we place this in the structure

**Comment by ipopescu** [comment]
I am not aware of any materials already written on this topic. This work probably needs to be done from scratch, but it's good to check with the rest of the team as well.

**Comment by ACStone-MTS** [comment]
The only material I am aware of is the Casper v EVM Google Spreadsheet that it appears @Adrian-Wrona has access to.

**Comment by ghost** [comment]
Closing in favor of https://github.com/casper-network/docs/issues/1176.
