### ISSUE TITLE
Build dApps/Explanation of session code and contract code in context of the dAaps

### ISSUE THREAD

**Issue by ghost** [casper-network/docs-new#44]
.

**Comment by dylanireland** [comment]
@casper-network/tiger-team This is now almost complete, but is someone able to write a session code example (preferably one that interacts with a hypothetical "Hello World contract").
I've placed a marker in the file, it needs to go on the very last line.

**Comment by dylanireland** [comment]
Also, as is, this file describes contracts and session code in the context of dApps, so therefore shows how to install, call, and query contracts (and just install session code) but it's once again become repetitive, there are examples of this in the Unified SDK document.

**Comment by dylanireland** [comment]
Also this branch fails CI/CD because */resources/tutorials/beginner/querying-network/* links to */design/* which throws an error. This is NOT part of this PR.

**Comment by Adrian-Wrona** [comment]
@jonas089 please add a RUST example here

**Comment by jonas089** [comment]
@Adrian-Wrona is there a reason why I can't see this issue in ZenHub?

**Comment by jonas089** [comment]
I added a reference to the existing tutorial on writing session code and wrote a paragraph explaining how and when to use it with the SDK.

**Comment by jonas089** [comment]
Fixing my own paragraph:
Session code can not be called with the sdk as it's only executed once and does not 'live' on the chain.

**Comment by Adrian-Wrona** [comment]
@dylanireland please review what @jonas089 did and eventually submit a PR

**Comment by ghost** [comment]
This page was supposed to be available under:
 - https://staging.docs.casper.network/developers/dapps/explanation-session-and-contract/
 - https://docs.casper.network/developers/dapps/explanation-session-and-contract/

However, changes are stuck on the unmerged branch [44-explanation-of-session-code-and-contract-code-in-context-of-dapps](https://github.com/casper-network/docs-new/compare/44-explanation-of-session-code-and-contract-code-in-context-of-dapps).

@Adrian-Wrona how do we proceed here? Should I backport those changes with PR to `docs` repository?
@jonas089 FYI

**Comment by ghost** [comment]
Confirmed with @jonas089, changes are obsolete now. I talked with @ipopescu about "_Explanation of session code and contract code in context of the dAaps_", and we concluded there is no need for such page.
